export enum IncomingPacketIds {
  // Handshake
  SSO_TICKET = 1,
  CLIENT_HELLO = 2,
  CLIENT_PONG = 3,

  // Rooms
  ROOM_ENTER = 100,
  ROOM_LEAVE = 101,
  ROOM_MOVE = 102,
  ROOM_CHAT = 103,
  ROOM_SHOUT = 104,
  ROOM_WHISPER = 105,
  ROOM_LOOK_AT = 106,
  ROOM_ACTION = 107,
  ROOM_DANCE = 108,

  // Navigator
  NAVIGATOR_SEARCH = 200,
  NAVIGATOR_CREATE_ROOM = 201,

  // Catalog
  CATALOG_GET_INDEX = 300,
  CATALOG_GET_PAGE = 301,
  CATALOG_PURCHASE = 302,

  // Inventory
  INVENTORY_GET = 400,
  INVENTORY_PLACE_ITEM = 401,
  INVENTORY_MOVE_ITEM = 402,
  INVENTORY_PICKUP_ITEM = 403,

  // Users
  USER_INFO = 500,
  USER_LOOK = 501,
  USER_MOTTO = 502,

  // Messenger
  MESSENGER_INIT = 600,
  MESSENGER_SEND = 601,
  MESSENGER_ACCEPT = 602,
  MESSENGER_DECLINE = 603,

  // Trading
  TRADE_START = 700,
  TRADE_OFFER = 701,
  TRADE_ACCEPT = 702,
  TRADE_CANCEL = 703,

  // Kodexa Marketplace
  MARKETPLACE_LIST = 800,
  MARKETPLACE_BUY = 801,
  MARKETPLACE_SEARCH = 802,

  // Kodexa Wired
  WIRED_SAVE_SCRIPT = 900,
  WIRED_GET_SCRIPT = 901,
}

export enum OutgoingPacketIds {
  // Handshake
  AUTH_OK = 1,
  AUTH_FAILED = 2,
  SERVER_PING = 3,

  // Rooms
  ROOM_DATA = 100,
  ROOM_HEIGHTMAP = 101,
  ROOM_USERS = 102,
  ROOM_USER_ADDED = 103,
  ROOM_USER_REMOVED = 104,
  ROOM_USER_MOVED = 105,
  ROOM_USER_CHAT = 106,
  ROOM_USER_STATUS = 107,
  ROOM_USER_DANCE = 108,
  ROOM_ITEMS = 109,
  ROOM_ITEM_ADDED = 110,
  ROOM_ITEM_REMOVED = 111,
  ROOM_ITEM_MOVED = 112,
  ROOM_WALL_ITEMS = 113,

  // Navigator
  NAVIGATOR_RESULTS = 200,
  NAVIGATOR_ROOM_CREATED = 201,

  // Catalog
  CATALOG_INDEX = 300,
  CATALOG_PAGE_DATA = 301,
  CATALOG_PURCHASE_OK = 302,
  CATALOG_PURCHASE_ERROR = 303,

  // Inventory
  INVENTORY_DATA = 400,
  INVENTORY_ITEM_ADDED = 401,
  INVENTORY_ITEM_REMOVED = 402,

  // Users
  USER_DATA = 500,
  USER_CREDITS = 501,
  USER_CURRENCIES = 502,

  // Messenger
  MESSENGER_FRIENDS = 600,
  MESSENGER_MESSAGE = 601,
  MESSENGER_FRIEND_UPDATE = 602,

  // Trading
  TRADE_OPEN = 700,
  TRADE_UPDATE = 701,
  TRADE_COMPLETED = 702,
  TRADE_CANCELLED = 703,

  // Kodexa Marketplace
  MARKETPLACE_LISTINGS = 800,
  MARKETPLACE_BUY_OK = 801,

  // Kodexa
  KX_NOTIFICATION = 950,
  KX_ACHIEVEMENT = 951,
}
